language: java
jdk: oraclejdk8
sudo: required
dist: trusty
before_install: "./.travis.before_install.sh"
branches:
  only:
  - master
  - 3.0
  - 2.1
  - 1.2
cache:
  directories:
  - "$HOME/.m2"
before_cache:
- rm -rf "$HOME/.m2/repository/com/vaadin/*spring*"

