language: java
jdk: oraclejdk7
sudo: required
dist: trusty
before_install: "./.travis.before_install.sh"
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
before_cache:
- rm -rf "$HOME/.m2/repository/com/vaadin/*spring*"

